### ISSUE TITLE
CUDA out of memory. Any workaround?

### ISSUE THREAD

**Issue by eperezv** [RasmussenLab/vamb#295]
Hi,
I'm trying avamb to get bins from my data and it seems I am getting an memory error from CUDA in an almost final step. The error is below. I think I could run it without CUDA and probably it would work but I wonder if there is something that I could specify in the config to try to make it work in my server.

The error is this:
 
```
Traceback (most recent call last):
  File "/home/eduardo/miniconda3/envs/avamb/bin/vamb", line 33, in <module>
    sys.exit(load_entry_point('vamb', 'console_scripts', 'vamb')())
  File "/home/eduardo/tools/avamb/vamb/vamb/__main__.py", line 1390, in main
    run(
  File "/home/eduardo/tools/avamb/vamb/vamb/__main__.py", line 869, in run
    cluster(
  File "/home/eduardo/tools/avamb/vamb/vamb/__main__.py", line 637, in cluster
    cluster_generator = vamb.cluster.ClusterGenerator(
  File "/home/eduardo/tools/avamb/vamb/vamb/cluster.py", line 227, in __init__
    torch_matrix = torch_matrix.cuda()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 5.54 GiB (GPU 0; 5.79 GiB total capacity; 0 bytes already allocated; 5.23 GiB free; 0 bytes reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[Sat Mar  2 00:15:05 2024]
Error in rule run_avamb:
    jobid: 7
    input: avamb_outdir/contigs.flt.fna.gz, avamb_outdir/abundance.npz
    output: avamb_outdir/avamb, avamb_outdir/avamb/aae_z_clusters.tsv, avamb_outdir/avamb/aae_y_clusters.tsv, avamb_outdir/avamb/vae_clusters.tsv, avamb_outdir/avamb/contignames, avamb_outdir/avamb/lengths.npz
    log: avamb_outdir/tmp/avamb_finished.log, avamb_outdir/log/run_avamb.out, avamb_outdir/log/run_avamb.err (check log file(s) for error details)
    conda-env: avamb
    shell:
        
        rm -rf avamb_outdir/abundances
        rm -rf avamb_outdir/contigs.flt.dict
        rm -f avamb_outdir/contigs.flt.mmi
        rm -rf avamb_outdir/avamb 
        
        vamb --outdir avamb_outdir/avamb --fasta avamb_outdir/contigs.flt.fna.gz -p 10 --rpkm avamb_outdir/abundance.npz -m 1000 --minfasta 200000  --cuda  --model vae-aae --minfasta 200000  -o C --cuda
        mkdir -p avamb_outdir/Final_bins
        mkdir -p avamb_outdir/tmp/checkm2_all
        mkdir -p avamb_outdir/tmp/ripped_bins
        touch avamb_outdir/tmp/avamb_finished.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job run_avamb since they might be corrupted:
avamb_outdir/avamb, avamb_outdir/avamb/vae_clusters.tsv, avamb_outdir/avamb/contignames, avamb_outdir/avamb/lengths.npz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-02-29T161741.580908.snakemake.log
```

**Comment by jakobnissen** [comment]
It looks like you are clustering too many samples to fit on your GPU's memory. This can happen if you have a lot of samples and a GPU with a small amount of memory.

Vamb _should_ be pretty memory efficient, but I'm not 100% sure because it's a little hard to benchmark. From the error message it's trying to allocate 5.54 GiB. That corresponds to a latent space with ~5 million contigs. Is that correct?
You can try
* The default VAMB model uses less memory
* Use a bigger GPU, if you have one available

**Comment by eperezv** [comment]
Thank you for you response. My dataset is big, GPU's memory small and I tried with contigs of >1000 nt. So I have tried with contigs > 2000 nt and it works fine now.
